# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fisherInd <- function(Q, P, base_period) {
    .Call('PQindex_fisherInd', PACKAGE = 'PQindex', Q, P, base_period)
}

rcpp_hello <- function() {
    .Call('PQindex_rcpp_hello', PACKAGE = 'PQindex')
}

