# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

fisherInd <- function(Q, P, base_period) {
    .Call('PQindex_fisherInd', PACKAGE = 'PQindex', Q, P, base_period)
}

fisherIndfast <- function(Q, P, Q_consol, P_consol, Q_freq, P_freq) {
    .Call('PQindex_fisherIndfast', PACKAGE = 'PQindex', Q, P, Q_consol, P_consol, Q_freq, P_freq)
}

testfn <- function(Q_consol, Q_ind) {
    .Call('PQindex_testfn', PACKAGE = 'PQindex', Q_consol, Q_ind)
}

fisherIndfastest <- function(Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind) {
    .Call('PQindex_fisherIndfastest', PACKAGE = 'PQindex', Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind)
}

matmult_cpp <- function(X, Y) {
    .Call('PQindex_matmult_cpp', PACKAGE = 'PQindex', X, Y)
}

fisherIndfaster <- function(Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind) {
    .Call('PQindex_fisherIndfaster', PACKAGE = 'PQindex', Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind)
}

fisherIndfasterold <- function(Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind) {
    .Call('PQindex_fisherIndfasterold', PACKAGE = 'PQindex', Q_consol, P_consol, Q_freq, P_freq, Q_ind, P_ind)
}

fisherIndfullmat <- function(Q, P) {
    .Call('PQindex_fisherIndfullmat', PACKAGE = 'PQindex', Q, P)
}

rcpp_hello <- function() {
    .Call('PQindex_rcpp_hello', PACKAGE = 'PQindex')
}

